### ISSUE TITLE
海曼，建议命名空间首字母大写

### ISSUE THREAD

**Issue by xonze** [hightman/httpclient#1]
Hightman\Http\

**Comment by hightman** [comment]
为什么啊，对于纯单词我好像都习惯全小写，除非有多个单词。类似的 `yii` 也是这样处理，感觉比较美观。

**Comment by xonze** [comment]
PSR-0的建议，现在很多框架和类库都遵照PSR

**Comment by hightman** [comment]
印象中没要求要大写字母开头啊，而且我反对大写开头的原因是 Unix\* 和 Win32 对于文件名的大小写处理方法不一样，所以这些涉及文件名相关的都尽量全小写了。
