### ISSUE TITLE
Cannot use "parent" when current class scope has no parent

### ISSUE THREAD

**Issue by shamoguhun** [hightman/httpclient#3]
/**
     * Clear headers and apply defaults.
     */
    public function clearHeader()
    {
        parent::clearHeader();
        $this->applyDefaultHeader();
    }

**Comment by hightman** [comment]
fixed, thanks.

**Comment by shamoguhun** [comment]
但运行的时候提示找不到"parent"这个类

**Comment by shamoguhun** [comment]
顺便更新一下composer
