### ISSUE TITLE
      .

### ISSUE THREAD

**Issue by tuberboy** [hightman/httpclient#4]

**Comment by hightman** [comment]
if you use Request::addPostFile() to upload attachment, the request will be multipart/form-data.

**Comment by TuberBoy** [comment]
I am not clear about it.

how will i send post request? This code:
```
                                $eol = PHP_EOL;
				$BOUNDARY = rand_string(16);
				$BODY="";
				$BODY .= '------WebKitFormBoundary'.$BOUNDARY.$eol;
				$BODY .= 'Content-Disposition: form-data; name="user[username]"'.$eol.$eol;
				$BODY .= $UN.$eol;
				$BODY .= '------WebKitFormBoundary'.$BOUNDARY.$eol;
				$BODY .= 'Content-Disposition: form-data; name="user[password]"'.$eol.$eol;
				$BODY .= "Mahgtyu65@".$eol;
				$BODY .= '------WebKitFormBoundary'.$BOUNDARY.$eol;
				$BODY .= 'Content-Disposition: form-data; name="user[email]"'.$eol.$eol;
				$BODY .= $Email.$eol;
				$BODY .= '------WebKitFormBoundary'.$BOUNDARY.$eol;
				$BODY .= 'Content-Disposition: form-data; name="funnel"'.$eol.$eol;
				$BODY .= "standard".$eol;
				$BODY .= '------WebKitFormBoundary'.$BOUNDARY.$eol;
				$BODY .= 'Content-Disposition: form-data; name="guest_checkout_token"'.$eol.$eol;
				$BODY .= "undefined".$eol;      
				$BODY .= '------WebKitFormBoundary'.$BOUNDARY.'--';
```

**Comment by hightman** [comment]
?? You need not build request body manually, just call request API, such as Request::addPostField, Request::addPostFile. see https://github.com/hightman/httpclient#customize-request

**Comment by emma-eva** [comment]
> ?? You need not build request body manually, just call request API, such as Request::addPostField, Request::addPostFile. see https://github.com/hightman/httpclient#customize-request
> […](#)
> 在 2021年9月23日，18:12，Tuber Boy ***@***.***> 写道： ﻿ I am not clear about it. how will i send post request? This code: $eol = PHP_EOL; $BOUNDARY = rand_string(16); $BODY=""; $BODY .= '------WebKitFormBoundary'.$BOUNDARY.$eol; $BODY .= 'Content-Disposition: form-data; name="user[username]"'.$eol.$eol; $BODY .= $UN.$eol; $BODY .= '------WebKitFormBoundary'.$BOUNDARY.$eol; $BODY .= 'Content-Disposition: form-data; name="user[password]"'.$eol.$eol; $BODY .= "Mahgtyu65@".$eol; $BODY .= '------WebKitFormBoundary'.$BOUNDARY.$eol; $BODY .= 'Content-Disposition: form-data; name="user[email]"'.$eol.$eol; $BODY .= $Email.$eol; $BODY .= '------WebKitFormBoundary'.$BOUNDARY.$eol; $BODY .= 'Content-Disposition: form-data; name="funnel"'.$eol.$eol; $BODY .= "standard".$eol; $BODY .= '------WebKitFormBoundary'.$BOUNDARY.$eol; $BODY .= 'Content-Disposition: form-data; name="guest_checkout_token"'.$eol.$eol; $BODY .= "undefined".$eol; $BODY .= '------WebKitFormBoundary'.$BOUNDARY.'--'; — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

It's not a solution... I am fetching problem. Show me exact example code. Ho to use boundary in your post field.

**Comment by TuberBoy** [comment]
May be it's like this:

$request->addPostField('Content-Disposition: form-data; name="user[username]"', 'usushdhf');
$request->addPostField('Content-Disposition: form-data; name="user[password]"', 'Pass266@');
$request->addPostField('Content-Disposition: form-data; name="user[email]"', 'mckjgag@mails.shop');
$request->addPostField('Content-Disposition: form-data; name="funnel"', 'standard');
$request->addPostField('Content-Disposition: form-data; name="guest_checkout_token"', 'undefined');
