### ISSUE TITLE
https url not working

### ISSUE THREAD

**Issue by emma-eva** [hightman/httpclient#5]
http tcp url working but https ssl url not working in xampp. May be have to add cer/pem certificate in your code. How to generate and add certificate in your code?

**Comment by emma-eva** [comment]
If you have not time to reply/contribute it then plz delete it from github...tnx

**Comment by hightman** [comment]
Sorry, custom certificate is not currently supported, I will add this feature soon.

**Comment by hightman** [comment]
In order to support tcp connection reusing and socks5 proxy, It is difficult to add support for custom SSL context options.

**Comment by hightman** [comment]
Now you can try to use `v1.9`, and specify context options (such as SSL local_cafile ...), example code:

```php
$request = new Request('https://www.your.host/request/uri');
$request->setMethod('POST');
$request->setHeader('user-agent', 'test robot');

// specify context options of connect, such as SSL options
$request->contextOptions = [
    'ssl' => ['verify_peer_name' => false, 'local_cert' => '/path/to/file.pem'],
];
```

more informations about context, see: https://www.php.net/manual/en/context.php

**Comment by emma-eva** [comment]
local cert not working 😭

Also plz add http and https auth proxy function.
Example:

function connect_to_http_proxy($host, $port, $destination, $creds=null) {
        $context = stream_context_create(
            ['ssl'=> ['verify_peer'=> false, 'verify_peer_name'=> false]]
        );
        $soc = stream_socket_client(
            "tcp://$host:$port", $errno, $errstr, 20, 
            STREAM_CLIENT_CONNECT, $context
        );
        if ($errno == 0) {
            $auth = $creds ? "Proxy-Authorization: Basic ".base64_encode($creds)."\r\n": "";
            $connect = "CONNECT $destination HTTP/1.1\r\n$auth\r\n";
            fwrite($soc, $connect);
            $rsp = fread($soc, 1024);
            if (preg_match('/^HTTP\/\d\.\d 200/', $rsp) == 1) {
                return $soc;
            }
            echo "Request denied, $rsp\n";
            return false;
        }
        echo "Connection failed, $errno, $errstr\n";
        return false;
    }
    
    $host = "proxy IP";
    $port = "proxy port";
    $destination = "chat.freenode.net:6697";
    $credentials = "user:pass";
    $soc = connect_to_http_proxy($host, $port, $destination, $credentials);
    if ($soc) {
        stream_socket_enable_crypto($soc, true, STREAM_CRYPTO_METHOD_ANY_CLIENT);
        fwrite($soc,"USER test\nNICK test\n");
        echo fread($soc, 1024);
        fclose($soc);
    }

**Comment by hightman** [comment]
Try to specify proxy via stream context options, see https://www.php.net/manual/en/context.http.php

**Comment by emma-eva** [comment]
> Try to specify proxy via stream context options, see https://www.php.net/manual/en/context.http.php
> […](#)
> 在 2021年10月3日，19:11，emma-eva ***@***.***> 写道： ﻿ local cert not working 😭 Also plz add http and https auth proxy function. Example: function connect_to_http_proxy($host, $port, $destination, $creds=null) { $context = stream_context_create( ['ssl'=> ['verify_peer'=> false, 'verify_peer_name'=> false]] ); $soc = stream_socket_client( "tcp://$host:$port", $errno, $errstr, 20, STREAM_CLIENT_CONNECT, $context ); if ($errno == 0) { $auth = $creds ? "Proxy-Authorization: Basic ".base64_encode($creds)."\r\n": ""; $connect = "CONNECT $destination HTTP/1.1\r\n$auth\r\n"; fwrite($soc, $connect); $rsp = fread($soc, 1024); if (preg_match('/^HTTP/\d.\d 200/', $rsp) == 1) { return $soc; } echo "Request denied, $rsp\n"; return false; } echo "Connection failed, $errno, $errstr\n"; return false; } $host = "proxy IP"; $port = "proxy port"; $destination = "chat.freenode.net:6697"; $credentials = "user:pass"; $soc = connect_to_http_proxy($host, $port, $destination, $credentials); if ($soc) { stream_socket_enable_crypto($soc, true, STREAM_CRYPTO_METHOD_ANY_CLIENT); fwrite($soc,"USER test\nNICK test\n"); echo fread($soc, 1024); fclose($soc); } — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

It's not working.... I have to use proxy username and password. Plz show me example how to i send auth request in your code. Thanks

**Comment by emma-eva** [comment]
I tried like this:
`$request->contextOptions = [
    'http' => ['proxy' => 'tcp://'.$PROXY_RACK_DNS.':'.$PROXY_RACK_PORT, 'request_fulluri' => true, 'header' => 'Proxy-Authorization: Basic '.$basicAuth]
];`

But not working

**Comment by hightman** [comment]
Yes, this way does not work. And http proxy supports may need to be re-implemented, sorry.

> I tried like this: `$request->contextOptions = [ 'http' => ['proxy' => 'tcp://'.$PROXY_RACK_DNS.':'.$PROXY_RACK_PORT, 'request_fulluri' => true, 'header' => 'Proxy-Authorization: Basic '.$basicAuth] ];`
> 
> But not working

**Comment by emma-eva** [comment]
I tried also using this code, It's working.

```$auth = base64_encode($ProxyUserName.':'.$ProxyPassword);
$a = stream_context_create(['http' => ['proxy' => "tcp://$PROXY_RACK_DNS:$PROXY_RACK_PORT", 'request_fulluri' => true, 'header' => "Proxy-Authorization: Basic ".$auth]]);
$url = "http://ip-api.com/json";
echo file_get_contents($url, null, $a);
```
Plz solve it in your code. I want to use your code.

**Comment by emma-eva** [comment]
Any solution? plz check above comment.

**Comment by hightman** [comment]
I have tried to solve this problem, but it still cannot handle HTTPS requests. Because we make HTTP request manualy in TCP connection. 

I suggest you use CURL extension in this case.

**Comment by emma-eva** [comment]
They doing it also but why can't you do it?
Check this: 

https://github.com/shtse8/easyrequest
https://github.com/shtse8/easyrequest/blob/master/src/Handler/Socket.php

https://github.com/weird/HttpClient/blob/master/HttpClient.php

**Comment by tuberboy** [comment]
Just follow this codes, i hope so you can make http proxy support `Proxy-Authorization: Basic`

1.) https://github.com/shtse8/easyrequest/blob/master/src/Handler/Socket.php

2.) https://github.com/weird/HttpClient/blob/master/HttpClient.php

**Comment by hightman** [comment]
In this way, HTTPS request still cannot be correct handled via PROXY_HTTP.

I have not enough time to make a full testing, you can implement this feature and create pull-request from github.

**Comment by emma-eva** [comment]
https request working in hosting server... Its enough. Just add http auth.. Proxy support. Thanks

**Comment by emma-eva** [comment]
As i see that you updated sometimes ago but not seeing http proxy auth support code

**Comment by hightman** [comment]
en, I will try when I have time, please wait a short while.

**Comment by emma-eva** [comment]
Ok, waiting... But add it as quickly as possible. Bcz my work stopped for that... I don’t like curl and any others library... I like your httpclient.

**Comment by hightman** [comment]
> Ok, waiting... But add it as quickly as possible. Bcz my work stopped for that... I don’t like curl and any others library... I like your httpclient.

Why use this library so persistently, you can try to use branch `proxy-wip`, but there is still a small bug with some SSL sites, it seems PHP-bug with non-blocking stream.

**Comment by emma-eva** [comment]
Just waste your last time to add http proxy support.... If you got time in future then upgrade more... Thanks

**Comment by hightman** [comment]
Use v1.11 plz... It supports socks5/socks4/http proxy now, and works well with HTTPS.

**Comment by emma-eva** [comment]
V1.11 will support http proxy authentication username and password?

**Comment by hightman** [comment]
yes! It is released, you can fetch from master branch.

**Comment by emma-eva** [comment]
Getting http proxy Authentication error:
```
    [status] => 400
    [statusText] => Bad Request
    [error] => Proxy communication error: 407 Proxy Authentication Required
    [body] => 
    [timeCost] => 0.31800293922424
    [url] => http://ip-api.com/json
    [numRedirected] => 0
    [_headers:protected] => Array
        (
        )

    [_cookies:protected] => Array
        (
        )
```
Trying like this:
```
$http = new Client();
Connection::useProxy('http://username:password@proxy.packetstream.io:31112');
Client::debug('open');
$csr = $http->get('http://ip-api.com/json');
echo '<pre>'; print_r($csr);
```

**Comment by hightman** [comment]
Sorry, the authentication code is missing, fixed now.
> Getting http proxy Authentication error:

**Comment by emma-eva** [comment]
It's working, great job bro. Can you help me to reverse engineering an android app? I need app private api... I am ready to pay you. Thanks

**Comment by hightman** [comment]
… sorry I cant do that.
