### ISSUE TITLE
setJsonBody() multiple array issues

### ISSUE THREAD

**Issue by gitaccxz** [hightman/httpclient#8]
Its `PATCH` request.

This is my json post data
```
{"user": {"profile_attributes": {"one_liner": "'.$title.'"}}}
```
i am trying like this but not working:
```
$request->setJsonBody(["user" => ["profile_attributes" => ["one_liner" => $title]]]);
```

**Comment by hightman** [comment]
see https://github.com/hightman/httpclient/blob/dcc4f476f7c20dd445df43a4f6988227a841a909/src/Request.php#L209

now only PUT and POST requests has body data.

**Comment by gitaccxz** [comment]
No PATCH request data. Plz add it

**Comment by gitaccxz** [comment]
i added it. Thanks
